version: '3'

services:
  mssql-server-linux:
    container_name: mssql-server-container3
    image: microsoft/mssql-server-linux:latest
    volumes:
      - ./data-mssql:/var/opt/mssql
    environment:
      SA_PASSWORD: "PajaPatak123"
      ACCEPT_EULA: "Y"
      MSSQL_PID:   "Developer"
    ports:
      - "2433:1433"