version: '3.4'

services:
  withdatabaseasyncdockerized:
    image: ${DOCKER_REGISTRY-}databasedockerized
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "5202:80"
    networks:
      - rs2mreza
    depends_on:
      - mssqlserver

  mssqlserver:
    container_name: mssql-server-container4
    image: microsoft/mssql-server-linux:latest
    volumes:
      - ./data-mssql:/var/opt/mssql
    environment:
      SA_PASSWORD: "PajaPatak123"
      ACCEPT_EULA: "Y"
      MSSQL_PID:   "Developer"
    ports:
      - "2433:1433"
    networks:
      - rs2mreza

networks:
  rs2mreza:
    driver: "bridge"
